name: GitHub Projects Automation

on:
  pull_request:
    types: [closed]

jobs:
  move-issue-to-done:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Step 1: Checks out the repository code for access if needed

      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "column_id": "PROJECT_COLUMN_ID",
              "content_type": "Issue",
              "content_id": "${{ github.event.issue.id }}"
            }' \
            https://api.github.com/projects/columns/PROJECT_COLUMN_ID/cards
        # Step 2: If PR is merged, moves the linked issue to the Done column
